export const MoviesActionTypes = {
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIES_START: 'GET_MOVIES_START',
  GET_MOVIES_FINISH: 'GET_MOVIES_FINISH',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  SET_SORT_BY_FILTER: 'SET_SORT_BY_FILTER',
} as const;
